run:
  timeout: 5m
  tests: true

output:
  format: colored-line-number

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
