name: PR Checks

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pull-requests: read
  security-events: write

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml
    secrets: inherit
